# model configuration
model_name_or_path: "data/outputs/sft/setting_1/stage_1/checkpoint-216"
stage: 2

# dataset configuration
data_dir: "data/train_data"

# training configuration
seed: 42
# train
do_train: true
output_dir: "data/outputs/sft/setting_1/stage_2"
bf16: true
num_train_epochs: 10
per_device_train_batch_size: 128
gradient_accumulation_steps: 2
optim: adamw_torch
weight_decay: 1.0e-4
learning_rate: 5.0e-4
lr_scheduler_type: cosine
warmup_steps: 28
logging_steps: 1
save_strategy: "steps"
save_steps: 100
report_to: "tensorboard"
# validation
do_eval: true
per_device_eval_batch_size: 128
eval_steps: 20
eval_strategy: "steps"
eval_accumulation_steps: 16