# model configuration
model_name_or_path: "model_configs/model_1"
processor_name_or_path: "model_configs/model_1"
embedding_path: "data/item_embeddings/naive_Qwen3-Embedding-0.6B.npy"
stage: 1

# dataset configuration
data_dir: "data/run_data"

# training configuration
seed: 42
# train
do_train: true
output_dir: "data/outputs/setting_2/stage_1"
bf16: true
num_train_epochs: 4
per_device_train_batch_size: 128
gradient_accumulation_steps: 2
optim: adamw_torch
weight_decay: 1.0e-4
learning_rate: 5.0e-4
# lr_scheduler_type: cosine
lr_scheduler_type: constant
logging_steps: 1
save_strategy: "epoch"
# save_strategy: "steps"
# save_steps: 100
report_to: "tensorboard"
# validation
do_eval: true
per_device_eval_batch_size: 128
eval_steps: 20
eval_strategy: "steps"
eval_accumulation_steps: 16